### ISSUE TITLE
Agregar sonido de cambio de nivel

### ISSUE THREAD

**Issue by YsaLuna** [GameNova-Studio/path-to-the-throne#111]
"Incluir un efecto de sonido que se reproduzca al cambiar de un nivel a otro.
Se pueden encontrar sonidos de uso gratuito en https://freesound.org/ (siempre chequear que cuente con el tag: creative commons 0)
Pista: todos los cambios de niveles se realizan desde el SceneChanger, puede ser un buen lugar donde hacer este cambio."

**Comment by Chox13** [comment]
**TODOS LOS SONIDOS PERTENECEN A LA CATEGORÍA CREATIVE COMMONS**

Se ha añadido sonidos para el cambio de niveles:
![Image](https://github.com/user-attachments/assets/b45d7aed-5af0-4a12-b787-05f9959612ae)
Sonido de ataque del jugador: [https://freesound.org/people/PorkMuncher/sounds/263595/](url)
Sonido de la casa derrumbándose: [https://freesound.org/people/NeoSpica/sounds/512243/](url)
